FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN sed -i 's@http://archive.ubuntu.com/ubuntu/@http://repo.huaweicloud.com/ubuntu/@g' /etc/apt/sources.list && \
    sed -i 's@http://security.ubuntu.com/ubuntu/@http://repo.huaweicloud.com/ubuntu/@g' /etc/apt/sources.list && \
    apt-get update && apt-get install -y \
    # === 基础工具 ===
    build-essential \
    git \
    wget \
    curl \
    unzip \
    busybox \
    ca-certificates \
    ninja-build \
    python3 \
    python3-pip \
    python-is-python3 \
    locales \
    # === Qt6 核心依赖 (Runtime & Dev) ===
    libgl1-mesa-dev \
    libglib2.0-0 \
    libxkbcommon-x11-0 \
    libfontconfig1 \
    libdbus-1-3 \
    libssl-dev \
    # === Qt6 XCB 插件依赖 ===
    libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 \
    libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0 \
    libxcb-shape0 libxcb-glx0 libxcb-cursor0 \
    libx11-xcb-dev \
    libglu1-mesa-dev \
    libxrender-dev \
    libxi-dev && \
    # === 生成 Locale 防止编译警告 ===
    locale-gen en_US.UTF-8 && \
    # === 设置 Python 镜像源 ===
    mkdir -p /root/.pip && \
    echo "[global]" > /root/.pip/pip.conf && \
    echo "index-url = https://repo.huaweicloud.com/repository/pypi/simple/  " >> /root/.pip/pip.conf && \
    echo "trusted-host = repo.huaweicloud.com" >> /root/.pip/pip.conf && \
    # === 安装 aqtinstall 和 新版 CMake ===
    pip3 install cmake==3.27.9 aqtinstall && \
    # === 使用 aqt 下载 Qt 6.5.3 ===
    mkdir -p /opt/qt6 && \
    aqt install-qt linux desktop 6.5.3 gcc_64 --outputdir /opt/qt6 && \
    # === 下载并编译安装 QScintilla 2.14.1 ===
    wget -q https://www.riverbankcomputing.com/static/Downloads/QScintilla/2.14.1/QScintilla_src-2.14.1.zip   && \
    unzip -q QScintilla_src-2.14.1.zip && \
    cd QScintilla_src-2.14.1/src && \
    export PATH=/opt/qt6/6.5.3/gcc_64/bin:$PATH && \
    qmake && \
    make -j$(nproc) && \
    make install && \
    # === 系统 ===
    cd ../.. && \
    rm -rf QScintilla_src-2.14.1* && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV QT_PATH=/opt/qt6/6.5.3/gcc_64
ENV PATH=$QT_PATH/bin:$PATH
ENV LD_LIBRARY_PATH=$QT_PATH/lib:$LD_LIBRARY_PATH
ENV CMAKE_PREFIX_PATH=$QT_PATH/lib/cmake
ENV LANG=en_US.UTF-8

WORKDIR /app

CMD ["/bin/bash"]

